### ISSUE TITLE
version number incorrect 

### ISSUE THREAD

**Issue by dialt0n3** [blockonomics/prestashop-plugin#101]
after updating to v.1.7.9

version number still shows as v1.7.83 in the modules page.

**Comment by shivaenigma** [comment]
@DarrenWestwood  Please check

**Comment by DarrenWestwood** [comment]
The version is not updated in the database ps_module during the upgrade. Resetting the module from the modules page fixes this.
The error is not present when updating between previous versions eg v1.7.82 -> v1.7.83.

The issue is caused by incorrect sequential versioning of the module as using v1.7.84 or v1.7.90 works as expected.
