### ISSUE TITLE
Payment Address and info no longer visible in back office 

### ISSUE THREAD

**Issue by dialt0n3** [blockonomics/prestashop-plugin#102]
Since update to Prestashop 1.7.7.x Payment address and info as show below is no longer visible in order details in back office

https://github.com/blockonomics/prestashop-plugin/raw/master/views/img/screenshot-1.png

**Comment by shivaenigma** [comment]
Yes this is a bug and is not working as expected in PS 1.7. These details are supposed to be shown via [invoice.tpl](https://github.com/blockonomics/prestashop-plugin/blob/1.7/views/templates/hook/invoice.tpl) but seems to be not working with latest versions of PS

@cnohall please have a look

**Comment by cnohall** [comment]
I'll check it out and work on finding a solution.

**Comment by cnohall** [comment]
I found a way of fixing it. However, the formatting is a bit off. 

![Untitled](https://user-images.githubusercontent.com/36883813/114302771-7e3cfd00-9b05-11eb-9f14-44b2996a6a8a.png)

I'll correct the formatting and do some testing before creating a PR.

**Comment by shivaenigma** [comment]
Can we not show it in *View Invoice* ? Is that not working right now

**Comment by shivaenigma** [comment]
Seeing #103, The details show still be present even after the module gets deleted. This is the same way we have in Wordpress using Notes. Even if the module is present, the details of payment of existing can be easily seen in the order custom fields/notes. We should do the same in prestashop

**Comment by cnohall** [comment]
> Can we not show it in invoice details. Merchant can still see it by clicking on _View Invoice_ ? Is that not working right now

The _view invoice_ works, but only for accepted payments, as shown on the image below.

![invoices](https://user-images.githubusercontent.com/36883813/114513189-e3633080-9c74-11eb-8b04-ee3d832122b3.png)

However, dialt0n3 reported that the invoice info was no longer visible in order details. We have code that can do that, but since 1.7.7.x it hasn't been working.

**Comment by shivaenigma** [comment]
I did some research
- We should be able to add details into the payment details 
- Looks like this is also searchable form Order Search interface
![Screenshot(118)](https://user-images.githubusercontent.com/737092/114516560-26180f00-9c5b-11eb-9085-3de3699b850b.png)
 
This way even after our module is deleted the bitcoin transaction/address details are still visible and searchable.

However, this is only for payments with valid txid. Payments not having txid (not paid yet), customer should still be able to see/search bitcoin address of an order like in Wocoomerce. Let us analyze how this can be done, if it is complex we can take it up later

**Comment by cnohall** [comment]
Sounds good, I'll examine it closer and see if there is a practical way of implementing it.

**Comment by shivaenigma** [comment]
>I take it that we want to remove the previous code related to showing the bitcoin transaction/address details under the order info?

Yes lets remove the previous code

**Comment by cnohall** [comment]
I've done some research into how PrestaShop works and have found a couple of different ways of displaying the payment information.

We can store the information in the PrestaShop database under `ps_order_payment`, as shown on the image below. This way it's stored even if the module is removed. 
![image](https://user-images.githubusercontent.com/36883813/114694615-ad49ad80-9d55-11eb-864a-18d8d008cd4c.png)

However, it's tricky to change the labels **Card number**, **Card type**, **Expiration date**, **Cardholder name**.

![image](https://user-images.githubusercontent.com/36883813/114696907-2e09a900-9d58-11eb-9431-57a9e168afc7.png)

It is possible to change the labels with the help of "[How to override Back Office views](https://devdocs.prestashop.com/1.7/modules/concepts/templating/admin-views/)". This is quite complicated, but it's possible. 

Another solution is to store the information in the database as described above. But, that we display the payment details in a new window on top of the order page, similarly as before. This has the benefit of the order being searchable by its txid and address, and that the data is saved even if the module is deleted. However, it might create some confusion, since the data also will be shown under **Card number**, **Card type**, **Expiration date**, **Cardholder name**.

I'll continue to do investigate different methods and update the issue as I go.

**Comment by cnohall** [comment]
Using the [translation feature](https://devdocs.prestashop.com/1.7/development/internationalization/translation/) might also work, instead of overriding back office views. This way **Card number, Card type, Expiration date, Cardholder name** might be updated to more suitable labels. 

I'll look into if this is practical, and if it's possible to change the labels only for blockonomics orders, so that the shift doesn't affect the labels for card payments.

**Comment by cnohall** [comment]
It's possible to store the payment details in the `ps_order_invoice` table in `note`. Below is an image that shows how this manifests itself:

![image](https://user-images.githubusercontent.com/36883813/114847740-00386900-9e19-11eb-9d13-86cd1c1f11e4.png)

In the image below only clear text is used. It's possible to add links and use other HTML marking. 

This, however, still doesn't solve the search querys, for TXID and address. We can add a separate field for that, otherwise we will probably have to overwrite the controller. I will look into that more once we have the code regarding payment details ready.

**Comment by shivaenigma** [comment]
Looks good. We can see think about search later. Few things to keep in mind:

- Bitcoin address should be shown in note even when invoice tx hasn't been recorded. This is very useful for callback purposes
- All other fields which we were showing in [invoice.tpl](https://github.com/blockonomics/prestashop-plugin/blob/1.7/views/templates/hook/invoice.tpl) including *Payment Error* and *Transaction Link*

**Comment by cnohall** [comment]
I'm in the Final steps of testing. The functionality is already there. Just want to make sure that the changes don't introduce anything unexpected. 

I have a question about the formatting. Due to the width of the Note window, sometimes there are some line breaks that might look less than ideal. Here's an example:

![image](https://user-images.githubusercontent.com/36883813/115243352-cc817a00-a15d-11eb-91e5-16c586761ad7.png)

What are your thoughts on shortening _Bitcoin address_ into _BTC Address_? This is how it would look like:
![image](https://user-images.githubusercontent.com/36883813/115243297-bd023100-a15d-11eb-8804-def10a6520e2.png)

Also, as you may see there is no _payment method_ shown in the two examples above. This is because we now create the invoice before the payment is made. PrestaShop fetches the payment information from the `ps_order_payment` table. An entry in `ps_order_payment` for the order is only created after the payment is done. 

This is how it looks like after the payment is done:

![image](https://user-images.githubusercontent.com/36883813/115245735-37cc4b80-a160-11eb-878d-8b2fce88ed96.png)

**Comment by shivaenigma** [comment]
Lets keep *Bitcoin Address*  . Newer address which are now frequently used will be like (so it will anyway goto next row)
**bc1q5hthr4h9crnl0s3v4z735yvxxz2wwyvhylfg6v** 
Status is not required and can be removed

Is it displaying error when Amount paid is less than Cart Value?

**Comment by cnohall** [comment]
I removed status and kept _Bitcoin Address_. Displaying error works, here's how it looks like:

![image](https://user-images.githubusercontent.com/36883813/115342607-7d7f2780-a1e5-11eb-8153-cc48586b1c8a.png)

**Comment by shivaenigma** [comment]
I have merged this. However,  I am not very convinced that directly using prestashop system table is the correct way to manipulate invoice note. Perhaps this is better done using Prestashop class object ? Please do research, if we don't find answer we can ask question on prestashop forum or stackoverflow also

**Comment by cnohall** [comment]
Yes, I agree. As shown in #107 there is probably a better way that is in line with PrestaShop's standards. I'll research it and update the code accordingly.

**Comment by cnohall** [comment]
It's possible to get and manipulate the invoice note through the `Order` class. This has the benefit of being in line with the PrestaShop standard. However, the drawback is that the html tags are being striped. The result can be seen on the image below:

![image](https://user-images.githubusercontent.com/36883813/116505370-ae521180-a8f5-11eb-8331-b154a5e9b503.png)

**Comment by shivaenigma** [comment]
![Screenshot(126)](https://user-images.githubusercontent.com/737092/116524055-8dd58780-a8f4-11eb-9856-efecd2fc0571.png)

**Comment by cnohall** [comment]
I'll create PR for it.

**Comment by dialt0n3** [comment]
![image](https://user-images.githubusercontent.com/2801150/118213119-4e05b880-b43b-11eb-9970-d58bc1bf5049.png)
still showing blank in that area for me with newest version (1.7.91) prestashop ver 1.7.7.3

**Comment by dialt0n3** [comment]
@cnohall this should be re-opened
@blockonomics

**Comment by cnohall** [comment]
Hello @dialt0n3, thanks for reporting the issue. We have tried to recreate it, but have been unable to do it so far. Can we ask you to create a ticket at our [helpdesk](https://help.blockonomics.co/support/home) so that we can follow up on it closer?

Looking forward to working on finding a solution!
