### ISSUE TITLE
Prestashop is not displaying gap limit error

### ISSUE THREAD

**Issue by shivaenigma** [blockonomics/prestashop-plugin#122]
Instead a random 500 error is displayed on checkout confusing merchant

**Comment by thisisayush** [comment]
Hi @shivaenigma @DarrenWestwood ,

After replicating the issue, here's what's displayed in Client and Merchant Side.

Client Side:
![image](https://user-images.githubusercontent.com/22245433/141055078-12c020d7-00e6-494a-9948-19c98ef7c1af.png)

Merchant Side:
BTC checks are passed including test address generation because we use reset=1 to prevent index increment.

with reset=0

![141055866-5447ea8b-d306-4bd4-ad7c-ea0e8dbaf457](https://user-images.githubusercontent.com/22245433/141056247-ae6b3cf6-14f0-4dba-9a12-eff8dbd91db9.jpg)

 
with reset=1

![141055910-972acb77-06f7-456f-87c2-13f6bd9aae0d](https://user-images.githubusercontent.com/22245433/141056260-f90452c6-697c-4a2a-b06f-b84b84543883.jpg)

Possible Solutions might include:,
- Remove reset=1 from testSetup or,
- Give the merchant to option to configure settings for testing.
- Improve Client-side error page to display more information related to error.
- Log the errors in system and display them on admin panel.

**Comment by DarrenWestwood** [comment]
The client side error should be improved to also display the gap limit and temporary errors:
https://github.com/blockonomics/woocommerce-plugin/blob/master/js/app.js#L93-L94
https://github.com/blockonomics/woocommerce-plugin/blob/master/templates/blockonomics_checkout.php#L37-L41

**Comment by thisisayush** [comment]
![image](https://user-images.githubusercontent.com/22245433/141778370-b6660faa-ba8e-4c15-93ec-21e9c0b5a00b.png)

This looks okay?
