### ISSUE TITLE
Blank checkout page due to missing extension

### ISSUE THREAD

**Issue by blockonomics** [blockonomics/prestashop-plugin#64]
Missing php-intl extension. Installing extension is fixing it. We should remove code that is triggering this

**Comment by DarrenWestwood** [comment]
Code from plugin triggering the issue
https://github.com/blockonomics/prestashop-plugin/blob/ab7e5d86fdbe7aefabf5270bc23c616a04cfea4b/controllers/front/validation.php#L150

**Comment by DarrenWestwood** [comment]
Added an error message for users who do not have the dependency installed.

**Comment by DarrenWestwood** [comment]
Complete stack trace:
[error.txt](https://github.com/blockonomics/prestashop-plugin/files/3197661/error.when.sending.order.created.email.txt)

**Comment by blockonomics** [comment]
Note that we are using unncessary variables   `$mes` and `$mailVars` which are never used. Let try removing them also

**Comment by DarrenWestwood** [comment]
Error still occurs with unncessary variables replaced appropriattly with `NULL` and `array()`

New validateOrder:
`$blockonomics->validateOrder(
            (int) $cart->id,
            Configuration::get('BLOCKONOMICS_ORDER_STATE_WAIT'),
            $total,
            $blockonomics->displayName,
            NULL,
            array(),
            (int) $currency->id,
            false,
            $customer->secure_key
);`

**Comment by blockonomics** [comment]
Ok check why payment by cheque module is working
https://github.com/PrestaShop/cheque/blob/68477bbc6f977441e86cadf6db53693585561915/controllers/front/validation.php#L64

**Comment by DarrenWestwood** [comment]
The error is present with the payment by cheque module.
The root cause of the issue is the idn_to_ascii function running on the domain name from the email address. https://github.com/PrestaShop/PrestaShop/blob/develop/classes/Mail.php#L895

This error is only present in some versions of PrestaShop where the installer does not check if the extension is installed.
"it has always been required... but visibly it wasn't being enforced. It's a mandatory extension for composer.json, Symfony and also to send Mail."
PS fixed this the issue on their end here: https://github.com/PrestaShop/PrestaShop/pull/11937
